version: '3'

services:
  app:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]